### ISSUE TITLE
Display date in post template

### ISSUE THREAD

**Issue by Toxaris** [ps-mr/website#13]
The template for posts should display `{{ post.date }}`. Currently, the date is not displayed, but the first paragraph of news items only makes sense with the date displayed.

**Comment by Blaisorblade** [comment]
Is this still open?

**Comment by Toxaris** [comment]
This is fixed by 801003ddcdeff681dca0aff61f04ac8b6ab56739.

For reference: We now have two different styles for displaying the date:

 - if the post metadata includes `event`, we print the event info (`post.date`, `post.event.start`, `post.event.end`, and `post.event.location`) in an infobox near the upper-right corner of the text. This looks a bit like an infobox on wikipedia.
 - if the post metadata has no `event`, we print the `post.date` right-aligned below the heading. This looks a bit like a date in a letter.
