### ISSUE TITLE
Autolink disrespects syntactic structure

### ISSUE THREAD

**Issue by Toxaris** [ps-mr/website#18]
The member name autolinker fails to respect the syntactic structure of the pages. For testing, I put a literal string like `"Rendel"` in a liquid template in a page. The autolinker replaced the string literal by something like `"<a href= ...>"`.

**Comment by Blaisorblade** [comment]
Back from the digression: is autolinking still on? I've followed Cai's example [using manual annotations](https://github.com/ps-mr/website/blob/master/teaching/thesis.md), and I think it works fine (though we could use brief internal docs, if that's the approach), but apparently automatic formatting is still used elsewhere.

**Comment by Blaisorblade** [comment]
Good. Do we need to check any content to add annotations now?

**Comment by b-studios** [comment]
According to a folder diff of `_site` before and after disabling there are 20 modified pages. I can take care of that.

**Comment by b-studios** [comment]
If some of the links in 5d791c9 are not necessary, feel free to remove them.

**Comment by Toxaris** [comment]
Thanks for taking care of this.

Also thanks for implementing the autolinking extension in the first place. I think it was an interesting experiment.
