### ISSUE TITLE
Fix reference formatting

### ISSUE THREAD

**Issue by Toxaris** [ps-mr/website#19]
@Blaisorblade found some bugs with the reference formatting (https://github.com/ps-mr/website/commit/c2b89eced5a7f3845d6835e0d4f250c5acdb67f1#commitcomment-9514895):

- The pipeline misunderstands some TeX-isms, like \lambda or \\.
- Plus, Markus Kreutzer didn't publish at Haskell symposium, but see below:

> * Layout-sensitive Language Extensibility with SugarHaskell
> by Sebastian Erdweg, Felix Rieger, Tillmann Rendel, and Klaus Ostermann
> In Proceedings of Haskell Symposium 77(3): . ACM Press, 2012.
>
> * Statische Analyse von Produktlinien
> by Markus Kreutzer
> In Proceedings of Haskell Symposium 77(3): . ACM Press, 2012.

The whole thing likes to repeat all fields if they're not overriden — "77(3):" repeats over quite a few more publications. I'm guessing that's because `capture` is not `let` but something more dynamically scoped/imperative/whatever.

**Comment by Toxaris** [comment]
The problem with repeating fields is fixed. Fixing it revealed some other bugs where information is not properly displayed. I will look into them tonight.

**Comment by Blaisorblade** [comment]
Here are the scripts we used in Marburg (from Christian) to process references. I probably should put this elsewhere, but not sure where.

This is the bib2bib-based script for splitting the bibliography in sections (see #20):

```sh
MP=.
BIB2BIB=./bibtex2html-1.95-linux/bib2bib
SRCBIB=PS-Repo/ps.bib

$BIB2BIB -ob psdipl.bib -c '$type="MASTERSTHESIS" or $type="BACHELORTHESIS"' $SRCBIB
$BIB2BIB -ob psphd.bib -c '$type="PHDTHESIS" and not($key="OstermannPhD")' $SRCBIB
$BIB2BIB -ob pspub.bib -c 'not($type="MASTERSTHESIS" or $type="BACHELORTHESIS" or $type="PHDTHESIS")' $SRCBIB
```

Then, there was another script based on bibtex2html doing more processing. I'll try to put them up eventually, but here it is, inline for reference. What's maybe harder to reproduce (and we probably shouldn't try) is in fact bibtex2html treatment of TeX-isms—which are handled correctly in [Marburg page](http://www.uni-marburg.de/fb12/ps/publications), there's even a lambda there!

```sh
#!/bin/sh
. conf.inc
BIBTEX=./bibtex2html-1.95-linux/bibtex2html
TMP=.

./filterps.sh
$BIBTEX --no-abstract -s myalphalong -dl -nodoc -nf doi doi -o pspub pspub.bib
sed "s/<br \/>/ /g" pspub.html | sed "s/<dt>//g" | sed "s/<dl>//g" | sed "s/<\/dl>//g" | sed "s/<dd>/<li>/g" | sed "s/<\/dd>/<br \/>\&nbsp;<\/li>/g" | sed "s/<\/dt>//g" | sed "s/^\[<a name.*$//g" |   grep -v "This file was generated by" | grep -v "This document was automatically generated with bibtex2html" |   grep -v "filliatr\/bibtex2html" |       grep -v "with the following command:" |         fgrep -v "$BIBTEX" |    grep -v "This file has been generated by" | grep -v "@COMMENT{{" > pspub.html

$BIBTEX --no-abstract -s myalphalong -dl -nodoc -nf doi doi -o psdipl psdipl.bib
sed "s/<br \/>/ /g" psdipl.html | sed "s/<dt>//g" | sed "s/<dl>//g" | sed "s/<\/dl>//g" | sed "s/<dd>/<li>/g" | sed "s/<\/dd>/<br \/>\&nbsp;<\/li>/g" | sed "s/<\/dt>//g" | sed "s/^\[<a name.*$//g" |  grep -v "This file was generated by" |  grep -v "This document was automatically generated with bibtex2html" |  grep -v "filliatr\/bibtex2html" |       grep -v "with the following command:" |         fgrep -v "$BIBTEX" |    grep -v "This file has been generated by" | grep -v "@COMMENT{{"  > psdipl.html

$BIBTEX --no-abstract -s myalphalong -dl -nodoc -nf doi doi -o psphd psphd.bib
sed "s/<br \/>/ /g" psphd.html | sed "s/<dt>//g" | sed "s/<dl>//g" | sed "s/<\/dl>//g" | sed "s/<dd>/<li>/g" | sed "s/<\/dd>/<br \/>\&nbsp;<\/li>/g" | sed "s/<\/dt>//g" | sed "s/^\[<a name.*$//g" |   grep -v "This file was generated by" |  grep -v "This document was automatically generated with bibtex2html" |  grep -v "filliatr\/bibtex2html" |       grep -v "with the following command:" |         fgrep -v "$BIBTEX" |    grep -v "This file has been generated by" | grep -v "@COMMENT{{" > psphd.html

cat head.html > $NAME.html
echo '<h1>Publications</h1>' >> $NAME.html
echo '<h2>Journals / Conference</h2>' >> $NAME.html
echo '<div class="bib">' >> $NAME.html
cat pspub.html >> $NAME.html
echo '</div>' >> $NAME.html

echo '<h2>Dissertations</h2>' >> $NAME.html
echo '<div class="bib">' >> $NAME.html
cat psphd.html >> $NAME.html
echo '</div>' >> $NAME.html

echo "<h2>Diplom/Master' Theses</h2>" >> $NAME.html
echo '<div class="bib">' >> $NAME.html
cat psdipl.html >> $NAME.html
echo '</div>' >> $NAME.html
```

**Comment by Blaisorblade** [comment]
Forgot: thanks for the prompt response!

**Comment by Blaisorblade** [comment]
Looks better, only `.\ ` is missing. Should we just stop using those abbreviations in the .bib file, since they're ugly anyway?

**Comment by Toxaris** [comment]
I'll look into how we can extend the TeXisms that bibtex-ruby understands.

About .bib file aesthetics: Deep inside, I feel that one should abstract over common parts in .bib files, in order to make it easier to achieve a consistent presentation of references. Maybe I'm going to far in my [tsr.bib](https://github.com/Toxaris/Bibs/blob/master/tsr.bib), though.

**Comment by Toxaris** [comment]
I learned that TeXisms are handled by [inukshuk/latex-decode](https://github.com/inukshuk/latex-decode).

**Comment by Blaisorblade** [comment]
> About .bib file aesthetics: Deep inside, I feel that one should abstract over common parts in .bib files, in order to make it easier to achieve a consistent presentation of references. Maybe I'm going to far in my tsr.bib, though.

I also learned that from Christian, but I've never seen it to that extent.

**Comment by Blaisorblade** [comment]
Can we update the dependency (to 0.2.0) and throw out our code?

**Comment by Toxaris** [comment]
If it works, sure :)

**Comment by Blaisorblade** [comment]
One of those commits was indeed intended to close the issue — the revert commits wasn't.
