### ISSUE TITLE
Split publications by type

### ISSUE THREAD

**Issue by Toxaris** [ps-mr/website#20]
@Blaisorblade said:
> Also, the Marburg bibliography wasn't used directly, but divided into sections with a set of bib2bib-based scripts (which I did backup from Marburg).

We can easily do this in Liquid. Which sections should we have?

**Comment by Blaisorblade** [comment]
The sections are papers, PhD theses/dissertations, and other theses.

**Comment by Blaisorblade** [comment]
For reference: see http://www.uni-marburg.de/fb12/ps/publications.
