### ISSUE TITLE
Feature request: page aliases

### ISSUE THREAD

**Issue by yfcai** [ps-mr/website#26]
Is it possible to have multiple paths point to the same page? I want `research/functors` and `research/%20functors` to
1. point to same page
2. not generate duplicate items in the menu.

Alternatively, the web server may ignore all `%20` in URL paths.

Ultimate goal = make URL foolproof, where fool is defined to be anybody copying a URL with line break in it out of a PDF, instead of clicking on it.

**Comment by klauso** [comment]
> fool is defined to be anybody copying a URL with line break in it out of a PDF, instead of clicking on it.

I need to remember that one.

**Comment by Blaisorblade** [comment]
Have you tried committing a symlink? The page will be processed twice, but who cares about the extra computational load.
Alternatively, one could try having a 30X redirect.

**Comment by yfcai** [comment]
Tried symlink; it results in 2 items in menu bar.


2015-02-28 1:08 GMT+01:00 Paolo G. Giarrusso <notifications@github.com>:

**Comment by Toxaris** [comment]
There's no support for multiple URLs pointing to the same page, and I'm not motivated to add such support, sorry. However, here's a workaround that should work for your use case:

~~~
> md "research/ functors"
> echo Exact Content! > "research/ functors/index.html"
> jekyll build
> cat "_site/research/ functors/index.html"
Exact Content!
~~~

In other words, put the exact index.html file you want *without* a YAML frontmatter section, and it will get copied over to the site. In the index.hml, you can put a link or refresh to the real URL.

**Comment by Blaisorblade** [comment]
> I don't have control over the server, so if you really want a server-side redirect there, you have to talk to Harald.
> Please don't create any permanent redirects without checking back with me.

Hadn't you written that, I was going to try having an .htaccess file there with a 30X redirect. I'll abstain. `.htaccess` files seem to be used, the question is what's enabled there.

Otherwise, I agree with your suggestion.

**Comment by Toxaris** [comment]
The problem with *permanent* redirects is that they are *permanent*, that is, clients and proxies etc. store them *forever*. Before we put any, we want to think about our URL namespace.

**Comment by Toxaris** [comment]
What's the status of this. I don't see `research/ functors`, but maybe we can close this issue anyway? Please reopen if there's something to do here.
