### ISSUE TITLE
Discontinue http://ps-mr.github.io/

### ISSUE THREAD

**Issue by Toxaris** [ps-mr/website#3]
Now that we have the new site, we discontinue the temporary http://ps-mr.github.io/ after porting over all information.

EDIT:
To migrate:
- [x] Metaprogramming Seminar
- [x] PRG page
- [x] arguably, [the IPS website](http://yfcai.github.io/scala/) should be inline (right @yfcai)? But as long as we link to it from the new website, that's not a blocker.
- [x] update links from Vorlesungsverzeichnis (e.g. for my seminar)
- [x] fix main layout bugs if possible
- [ ] fill in this list more

**Comment by Toxaris** [comment]
What's the status of this?

**Comment by Blaisorblade** [comment]
Cai's gonna merge the one missing bit from the old website for his course.

**Comment by yfcai** [comment]
Cloned links to pages about Scala-Praktikum (IPS) via f53546cc8da298b1e302f3a4e2390126739798b2.

**Comment by Blaisorblade** [comment]
Anything left?

**Comment by Blaisorblade** [comment]
I suspect we just need to somehow "shutdown" http://ps-mr.github.io/.

**Comment by Toxaris** [comment]
I think we should replace http://ps-mr.github.io/ by a page that forwards / redirects / refreshes / whatevers to our new http://ps.informatik.uni-tuebingen.de.

**Comment by Blaisorblade** [comment]
The solution is described [here](https://help.github.com/articles/redirects-on-github-pages/) — it's not perfect, but I guess the difference would only matter (a bit) if http://ps-mr.github.io/ had ever been highly popular on Google. So I'm just gonna do that.

**Comment by Blaisorblade** [comment]
Cool, you can close issues across repos!
